{
  "name": "Marketing Software CRM",
  "env": {
    "NODE_VERSION": "18.x",
    "NPM_VERSION": "9.x"
  },
  "buildCommand": "chmod +x ./render/build.sh && ./render/build.sh",
  "startCommand": "chmod +x ./render/run.sh && ./render/run.sh",
  "envVarGroups": [
    {
      "name": "database",
      "envVars": [
        {
          "key": "DATABASE_URL",
          "value": "",
          "isSecret": true
        }
      ]
    },
    {
      "name": "authentication",
      "envVars": [
        {
          "key": "JWT_SECRET",
          "generateValue": true,
          "isSecret": true
        },
        {
          "key": "JWT_EXPIRES_IN",
          "value": "7d"
        }
      ]
    }
  ],
  "healthCheckPath": "/api/health"
}
