{
  "name": "Marketing Software CRM",
  "env": {
    "NODE_VERSION": "18.x",
    "NPM_VERSION": "9.x",
    "NODE_ENV": "production",
    "PORT": "10000",
    "DATABASE_URL": "postgresql://marketingdb_0a9i_user:UGWqFtrp6iiSqqRrl6fUGnpntfbsZAUn@dpg-cvgb76lrie7s73bnuck0-a/marketingdb_0a9i",
    "JWT_SECRET": "3e9af42b7820d384b4f8b0e5d91b0e1a87654321",
    "JWT_EXPIRES_IN": "7d",
    "ANALYTICS_ENABLED": "true",
    "LOG_LEVEL": "info"
  },
  "buildCommand": "chmod +x ./render/build.sh && ./render/build.sh",
  "startCommand": "chmod +x ./render/run.sh && ./render/run.sh",
  "healthCheckPath": "/api/health",
  "autoDeploy": true,
  "disk": {
    "name": "data",
    "mountPath": "/var/data",
    "sizeGB": 1
  }
}
