{
  "name": "Marketing Software CRM",
  "env": {
    "NODE_VERSION": "18.x",
    "NPM_VERSION": "9.x",
    "NODE_ENV": "production",
    "PORT": "10000"
  },
  "buildCommand": "chmod +x ./render/build.sh && ./render/build.sh",
  "startCommand": "chmod +x ./render/run.sh && ./render/run.sh",
  "envVarGroups": [
    {
      "name": "database",
      "envVars": [
        {
          "key": "DATABASE_URL",
          "value": "",
          "isSecret": true
        }
      ]
    },
    {
      "name": "authentication",
      "envVars": [
        {
          "key": "JWT_SECRET",
          "generateValue": true,
          "isSecret": true
        },
        {
          "key": "JWT_EXPIRES_IN",
          "value": "7d"
        }
      ]
    },
    {
      "name": "application",
      "envVars": [
        {
          "key": "NEXT_PUBLIC_APP_URL",
          "sync": "URL"
        },
        {
          "key": "API_URL",
          "sync": "URL"
        },
        {
          "key": "ANALYTICS_ENABLED",
          "value": "true"
        },
        {
          "key": "LOG_LEVEL",
          "value": "info"
        }
      ]
    }
  ],
  "healthCheckPath": "/api/health",
  "autoDeploy": true,
  "disk": {
    "name": "data",
    "mountPath": "/var/data",
    "sizeGB": 1
  }
}
